/*
 Simpslider v2.0 - jQuery slider for web developers
 author: Pavel A. Hryshayeu
 author email: gigatrop@gmail.com
 author site: http://psdvhtml.by
 plugin page: http://psdvhtml.by/simpslider
 license: GPL
*/

jQuery.fn.simpslider=function(L){function y(a){var b;a:{b=a.charAt(0).toUpperCase()+a.slice(1);var c=document.createElement("div");if(null==c.style[a]){var e=["Webkit","Moz","ms","webkit"],h;for(h in e)if(void 0!==c.style[e[h]+b]){b="-"+e[h].toLowerCase()+"-";break a}}b=""}return b+a}function M(a){var b={},c;for(c in a)a.hasOwnProperty(c)&&(b[y(c)]=a[c]);return b}function k(){var d=a.itemsSelector.split(","),b=l();l.each(d,function(a,e){b=n.find(e);if(b.length)return!1});return b}function q(){return k().first()}
function z(d){d=a.dots.eq(d).addClass(a.activeClass);a.dots.not(d).removeClass(a.activeClass)}function E(){if("fade"===a.effect){var d=k();d.css({display:"none",position:"absolute",left:0,top:0,zIndex:a.itemsZ,opacity:0});d.eq(a.startID?a.startID:a.curID).css({display:"block",zIndex:a.itemsZ+1,opacity:100})}}function F(){a.gpu2&&-1<N.indexOf("MSIE")&&(a.gpu2=!1);a.gpu2&&(a.gpu=!1)}function G(){a.itemsCount=k().length;E();A()}function H(d){l.extend(a,d);F();G()}function B(d,b,c){var e=k(),h=e.eq(b),
f=e.eq(d);e.not(h).not(f).css({display:"none",opacity:0,zIndex:a.itemsZ});c?(h.css({opacity:0,display:"none",zIndex:a.itemsZ}),f.css({display:"block",opacity:1,zIndex:a.itemsZ+2}),g(d,b)):(h.css({display:"block",opacity:1,zIndex:a.itemsZ+1}),a.fadePrevious&&h.animate({opacity:0},a.speed,a.easing),f.css({display:"block",opacity:0,zIndex:a.itemsZ+2}).animate({opacity:1},a.speed,a.easing,function(){g(d,b);h.css({display:"none"})}))}function t(d){if(!(2>a.itemsCount||a.moving||!a.infinit&&!a.curID))if(a.moveWidthVisible)if(0==
a.curID)a.infinit&&v(a.itemsCount-a.visibleCount);else{var b=a.curID-a.visibleCount;0>b&&(b=0);v(b)}else{b=function(){var e,b;"prev"!=a.touch.direction&&a.mover.prepend(k().last());if(a.horizontal){var x=d&&!a.touchSimple?a.touch.moveX-a.touch.x-a.moveWidth:-a.moveWidth;e=d&&!a.touchSimple?a.moveWidth-(a.touch.moveX-a.touch.x):a.moveWidth;b=0<e?a.speed:0;a.gpu2?(e=function(){a.mover.css(u,f+" "+b+"ms ease-in-out");a.mover.css(f,"");if(m)a.mover.one(m,function(){g(a.curID,c)});else setTimeout(function(){g(a.curID,
c)},b+200)},a.mover.css(f,"translateX("+x+"px)"),a.longReflow?setTimeout(e,100):e(a.mover[0].offsetWidth)):a.mover.css("left",x+"px").animate({left:"+="+e+"px"},b,a.easing,function(){g(a.curID,c)})}else x=d&&!a.touchSimple?a.touch.y-a.touch.moveY+a.moveHeight:a.moveHeight,e=d&&!a.touchSimple?a.moveHeight-(a.touch.moveY-a.touch.y):a.moveHeight,b=0<e?a.speed:0,a.gpu2?(e=function(){a.mover.css(u,f+" "+b/1E3+"s ease-in-out");a.mover.css(f,"");if(m)a.mover.one(m,function(){g(a.curID,c)});else setTimeout(function(){g(a.curID,
c)},b+200)},a.mover.css(f,"translateY(-"+x+"px)"),a.longReflow?setTimeout(e,100):e(a.mover[0].offsetWidth)):a.mover.css("top","-"+x+"px").animate({top:"+="+e+"px"},b,a.easing,function(){g(a.curID,c)})};a.moving=!0;a.direction="prev";var c=a.curID--;a.idHistory.unshift(a.curID);0>a.curID&&(a.curID=a.itemsCount-1);a.willID=a.curID;l.isFunction(a.doBefore)&&a.doBefore(a.willID,c);z(a.curID);"move"===a.effect?b():"fade"===a.effect&&B(a.curID,c)}}function r(d){if(!(2>a.itemsCount||a.moving))if(a.moveWidthVisible)if(a.curID==
a.itemsCount-a.visibleCount)a.infinit&&v(0);else{var b=a.curID+a.visibleCount;b+a.visibleCount>a.itemsCount&&(b=a.itemsCount-a.visibleCount);v(b)}else if(b=function(){var e,b;if(a.horizontal)if(a.gpu2)if(a.mover.css(u,f+" "+a.speed/1E3+"s ease-in-out"),a.mover.css(f,"translateX(-"+a.moveWidth+"px)"),m)a.mover.one(m,function(){a.mover.append(q());g(a.curID,c)});else setTimeout(function(){a.mover.append(q());g(a.curID,c)},a.speed+200);else e=d&&!a.touchSimple?a.moveWidth+(a.touch.moveX-a.touch.x):a.moveWidth,
b=0<e?a.speed:0,a.mover.animate({left:"-="+e+"px"},b,a.easing,function(){a.mover.append(q());a.mover.css("left",0);g(a.curID,c)});else if(a.gpu2)if(a.mover.css(u,f+" "+a.speed/1E3+"s ease-in-out"),a.mover.css(f,"translateY(-"+a.moveHeight+"px)"),m)a.mover.one(m,function(){a.mover.append(q());g(a.curID,c)});else setTimeout(function(){a.mover.append(q());g(a.curID,c)},a.speed+200);else e=d&&!a.touchSimple?a.moveHeight+(a.touch.moveY-a.touch.y):a.moveHeight,b=0<e?a.speed:0,a.mover.animate({top:"-="+
e+"px"},b,a.easing,function(){a.mover.append(q());a.mover.css("top",0);g(a.curID,c)})},a.infinit||a.curID!=a.itemsCount-a.visibleCount){a.moving=!0;a.direction="next";var c=a.curID++;a.idHistory.unshift(a.curID);a.curID>a.itemsCount-1&&(a.curID=0);a.willID=a.curID;l.isFunction(a.doBefore)&&a.doBefore(a.willID,c);z(a.curID);"move"===a.effect?b():"fade"===a.effect&&B(a.curID,c)}}function v(d,b){function c(){var b=a.curID-e;if(0>b){for(var d=-b,c=0;c<d;c++)a.mover.prepend(k().last());a.horizontal?a.gpu2?
(c=function(){a.mover.css(u,f+" "+h+"ms ease-in-out");a.mover.css(f,"");if(m)a.mover.one(m,function(){g(a.curID,e)});else setTimeout(function(){g(a.curID,e)},h+200)},a.mover.css(f,"translateX(-"+a.moveWidth*d+"px)"),a.longReflow?setTimeout(c,100):c(a.mover[0].offsetWidth)):a.mover.css("left","-"+a.moveWidth*d+"px").animate({left:0},h,a.easing,function(){g(a.curID,e)}):a.gpu2?(c=function(){a.mover.css(u,f+" "+h+"ms ease-in-out");a.mover.css(f,"");if(m)a.mover.one(m,function(){g(a.curID,e)});else setTimeout(function(){g(a.curID,
e)},h+200)},a.mover.css(f,"translateY(-"+a.moveHeight*d+"px)"),a.longReflow?setTimeout(c,100):c(a.mover[0].offsetWidth)):a.mover.css("top","-"+a.moveHeight*d+"px").animate({top:0},h,a.easing,function(){g(a.curID,e)})}else if(a.horizontal)if(a.gpu2)if(a.mover.css(u,f+" "+h+"ms ease-in-out"),a.mover.css(f,"translateX("+a.moveWidth*(e-a.curID)+"px)"),m)a.mover.one(m,function(){0<b&&a.mover.css(f,"").append(k().slice(0,b));g(a.curID,e)});else setTimeout(function(){0<b&&a.mover.css(f,"").append(k().slice(0,
b));g(a.curID,e)},h+200);else a.mover.animate({left:"+="+a.moveWidth*(e-a.curID)+"px"},h,a.easing,function(){0<b&&a.mover.css("left",0).append(k().slice(0,b));g(a.curID,e)});else if(a.gpu2)if(a.mover.css(u,f+" "+h+"ms ease-in-out"),a.mover.css(f,"translateY("+a.moveHeight*(e-a.curID)+"px)"),m)a.mover.one(m,function(){0<b&&a.mover.css(f,"").append(k().slice(0,b));g(a.curID,e)});else setTimeout(function(){0<b&&a.mover.css(f,"").append(k().slice(0,b));g(a.curID,e)},h+200);else a.mover.animate({top:"+="+
a.moveHeight*(e-a.curID)+"px"},h,a.easing,function(){0<b&&a.mover.css("top",0).append(k().slice(0,b));g(a.curID,e)})}if(d!=a.curID&&!(2>a.itemsCount||a.moving)){0<a.visibleCount&&a.moveWidthVisible&&!a.infinit&&d>a.itemsCount-a.visibleCount&&(d=a.itemsCount-a.visibleCount);a.moving=!0;a.direction="to";var e=a.curID;a.curID=d;a.idHistory.unshift(a.curID);a.willID=a.curID;l.isFunction(a.doBefore)&&a.doBefore(a.willID,e);var h=b?0:a.speed;z(a.curID);"move"===a.effect?c():"fade"===a.effect&&B(a.curID,
e,b)}}function g(d,b){a.gpu2&&a.mover.css(M({transition:"",transform:""}));a.moving=!1;A();l.isFunction(a.doAfter)&&a.doAfter(d,b)}function A(){a.infinit||(a.left.toggleClass(a.disabledClass,!a.curID||a.itemsCount<a.visibleCount),a.right.toggleClass(a.disabledClass,a.curID==a.itemsCount-a.visibleCount||a.itemsCount<a.visibleCount||0<a.visibleCount&&a.moveWidthVisible&&!a.infinit&&a.curID>=a.itemsCount-a.visibleCount))}function C(){D();a.iterator=setInterval(r,a.wait)}function D(){a.iterator&&clearInterval(a.iterator)}
var l=jQuery,n=l(this),p={},N=function(){var a=navigator.userAgent,b,c=a.match(/(opera|chrome|safari|firefox|msie|trident(?=\/))\/?\s*(\d+)/i)||[];if(/trident/i.test(c[1]))return b=/\brv[ :]+(\d+)/g.exec(a)||[],"MSIE "+(b[1]||"");if("Chrome"===c[1]&&(b=a.match(/\bOPR\/(\d+)/),null!=b))return"Opera "+b[1];c=c[2]?[c[1],c[2]]:[navigator.appName,navigator.appVersion,"-?"];null!=(b=a.match(/version\/(\d+)/i))&&c.splice(1,1,b[1]);return c.join(" ")}(),w=l.isFunction(l.fn.on)?"on":"live",m=function(){var a=
document.createElement("div"),b={WebkitTransition:"webkitTransitionEnd",MozTransition:"transitionend",OTransition:"oTransitionEnd otransitionend",transition:"transitionend"},c;for(c in b)if(void 0!==a.style[c])return b[c];return!1}(),f=y("transform"),u=y("transition"),a={moveWidth:n.width(),moveWidthPercent:0,moveHeight:n.height(),mover:n.find(".mover"),left:n.find(".left"),right:n.find(".right"),autoStart:!0,speed:800,easing:"swing",wait:5E3,stopOnHover:!0,dots:n.find("li"),itemsSelector:".item,img",
horizontal:!0,doAfter:null,doBefore:null,visibleCount:1,moveWidthVisible:!1,infinit:!0,effect:"move",itemsZ:1,touchLength:50,touchSimple:!1,activeClass:"active",disabledClass:"disabled",direction:"",itemsCount:0,curID:0,willID:0,idHistory:[0],moving:!1,iterator:0,stopped:!1,touchSupport:!0,touch:{started:!1,x:0,y:0,moveX:0,moveY:0,direction:""},responsive:!1,itemsWidthCoefficient:0,sidesRatio:0,itemsMarginPercent:0,fadePrevious:!1,gpu:!1,gpu2:!0,longReflow:!1,startID:0};(function(){l.extend(a,L);
F();var d=k();a.itemsCount=d.length;"static"==a.mover.css("position")&&a.mover.css("position","relative");a.gpu&&n.add(a.overflow).add(a.mover).add(d).css({transform:"translateZ(0)","backface-visibility":"hidden",perspective:1E3});E();a.startID&&v(a.startID,!0)})();a.responsive&&function(){function d(){var c=n.width();a.itemsWidthCoefficient&&b.css("width",c*a.itemsWidthCoefficient+"px");if(a.sidesRatio){var e=c*a.itemsWidthCoefficient*a.sidesRatio+"px";a.horizontal&&n.add(a.overflow).add(a.mover).add(b).height(e)}a.itemsMarginPercent&&
b.css("margin-left",c*a.itemsMarginPercent+"px");H({moveWidth:c*a.moveWidthPercent})}var b=k();a.moveWidthPercent||(a.moveWidthPercent=a.moveWidth/n.width());d();l(window).resize(function(){d();setTimeout(d,330);setTimeout(d,660);setTimeout(d,1E3)})}();A();var I=l.noop;(function(){var d,b=!0;I=function(c){c.preventDefault();b&&!a.left.hasClass(a.disabledClass)&&(t(),b=!1,d=setTimeout(function(){b=!0;clearTimeout(d)},200))}})();var J=l.noop;(function(){var d,b=!0;J=function(c){c.preventDefault();b&&
!a.right.hasClass(a.disabledClass)&&(r(),b=!1,d=setTimeout(function(){b=!0;clearTimeout(d)},200))}})();var K=l.noop;(function(){var a,b=!0;K=function(c){c.preventDefault();b&&(v(l(this).index()),b=!1,a=setTimeout(function(){b=!0;clearTimeout(a)},200))}})();a.left[w]("touchstart click",I);a.right[w]("touchstart click",J);a.dots[w]("touchstart click",K);(function(){function d(b){a.moving||(a.moving=!0,a.touch.started=!0,a.touch.x=b.originalEvent.touches[0].clientX,a.touch.y=b.originalEvent.touches[0].clientY,
a.touch.moveX=a.touch.x,a.touch.moveY=a.touch.y)}function b(){if(a.touch.started){a.touch.started=!1;a.moving=!1;var b=a.touch.moveX-a.touch.x,c=a.touch.moveY-a.touch.y;"move"!=a.effect||a.touchSimple||(a.horizontal?b>a.touchLength?t(!0):0<b?(a.curID--,0>a.curID&&(a.curID=a.itemsCount-1),a.touch.x=0,a.touch.moveX=b-a.moveWidth,r(!0)):b<-a.touchLength?r(!0):0>b&&(a.curID++,a.curID>a.itemsCount-1&&(a.curID=0),a.touch.x=0,a.touch.moveX=a.moveWidth+b,"next"==a.touch.direction&&a.mover.append(q()),t(!0)):
c>a.touchLength?t(!0):0<c?(a.curID--,0>a.curID&&(a.curID=a.itemsCount-1),a.touch.y=0,a.touch.moveY=c-a.moveHeight,r(!0)):c<-a.touchLength?r(!0):0>c&&(a.curID++,a.curID>a.itemsCount-1&&(a.curID=0),a.touch.y=0,a.touch.moveY=a.moveHeight+c,"next"==a.touch.direction&&a.mover.append(q()),t(!0)));if("fade"==a.effect||a.touchSimple)a.horizontal?(b>a.touchLength&&t(!0),b<-a.touchLength&&r(!0)):(c>a.touchLength&&t(!0),c<-a.touchLength&&r(!0));a.touch.direction=""}}function c(b){a.touch.started&&(10<a.touch.moveX-
a.touch.x&&b.preventDefault(),a.touch.moveX=b.originalEvent.touches[0].clientX,a.touch.moveY=b.originalEvent.touches[0].clientY,"move"!=a.effect||a.touchSimple||(a.horizontal?(b=a.touch.moveX-a.touch.x,0<b&&(b>a.moveWidth&&(b=a.moveWidth,a.touch.moveX=a.touch.x+b),"prev"!=a.touch.direction&&(a.mover.prepend(k().last()),a.touch.direction="prev")),"prev"==a.touch.direction&&(a.gpu2?a.mover.css("transform","translateX("+(b-a.moveWidth)+"px)"):a.mover.css("left",b-a.moveWidth+"px")),0>b&&(b<-a.moveWidth&&
(b=-a.moveWidth,a.touch.moveX=a.touch.x+b),"next"!=a.touch.direction&&("prev"==a.touch.direction&&a.mover.append(q()),a.touch.direction="next")),"next"==a.touch.direction&&(a.gpu2?a.mover.css("transform","translateX("+b+"px)"):a.mover.css("left",b+"px"))):(b=a.touch.moveY-a.touch.y,0<b&&(b>a.moveHeight&&(b=a.moveHeight,a.touch.moveY=a.touch.y+b),"prev"!=a.touch.direction&&(a.mover.prepend(k().last()),a.touch.direction="prev")),"prev"==a.touch.direction&&a.mover.css("top",b-a.moveHeight+"px"),0>b&&
(b<-a.moveHeight&&(b=-a.moveHeight,a.touch.moveX=a.touch.y+b),"next"!=a.touch.direction&&("prev"==a.touch.direction&&a.mover.append(q()),a.touch.direction="next")),"next"==a.touch.direction&&a.mover.css("top",b+"px"))))}a.touchSupport&&(a.mover[w]("touchstart",d),a.mover[w]("touchend",b),a.mover[w]("touchmove",c))})();a.autoStart&&C();a.autoStart&&a.stopOnHover&&n.mouseenter(D).mouseleave(function(){a.stopped||C()});p.stop=function(){D();a.stopped=!0};p.start=function(){C();a.stopped=!1};p.next=r;
p.prev=t;p.to=v;p.back=function(d){1<a.idHistory.length&&p.to(a.idHistory[1],d)};p.refresh=G;p.setParams=H;p.params=a;return p};